# Generated by Django 5.2.5 on 2026-05-20 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_tenant_access_key_tenant_invoice_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('company', 'Company Master'), ('supplier', 'Supplier Master'), ('product', 'Product Master'), ('stock', 'Stock & Batches')], max_length=20)),
                ('source_name', models.CharField(default='Text Copy-Paste', max_length=100)),
                ('records_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ROLLED_BACK', 'Rolled Back'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
