# Generated by Django 6.0.2 on 2026-05-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataMigration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationlog',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='migrationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('ROLLED_BACK', 'Rolled Back'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20),
        ),
    ]
