# Generated by Django 5.2.5 on 2026-06-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataMigration', '0002_migrationlog_error_message_and_more'),
        ('tenants', '0006_tenant_access_key_tenant_invoice_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True)),
                ('order', models.IntegerField()),
                ('data', models.JSONField()),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['job_id', 'order'], name='dataMigrati_job_id_c76fb0_idx')],
            },
        ),
    ]
