# Generated by Django 6.0.2 on 2026-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
