# Generated by Django 5.2.5 on 2026-05-13 07:18

from django.db import migrations, models, connection


def add_access_key_field(apps, schema_editor):
    """Safely add access_key field if it doesn't already exist."""
    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(tenants_tenant);")
            columns = [row[1] for row in cursor.fetchall()]
            column_exists = 'access_key' in columns
        else:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'tenants_tenant' 
                    AND column_name = 'access_key'
                );
            """)
            column_exists = cursor.fetchone()[0]
    
    if not column_exists:
        # Column doesn't exist, add it
        schema_editor.add_field(
            apps.get_model('tenants', 'Tenant'),
            models.CharField(blank=True, max_length=100, null=True, unique=True, name='access_key')
        )


def reverse_add_access_key(apps, schema_editor):
    """Reverse: remove access_key field if it exists."""
    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(tenants_tenant);")
            columns = [row[1] for row in cursor.fetchall()]
            column_exists = 'access_key' in columns
        else:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'tenants_tenant' 
                    AND column_name = 'access_key'
                );
            """)
            column_exists = cursor.fetchone()[0]
    
    if column_exists:
        schema_editor.remove_field(
            apps.get_model('tenants', 'Tenant'),
            'access_key'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_gst_number'),
    ]

    operations = [
        migrations.RunPython(add_access_key_field, reverse_add_access_key),
    ]
