# Generated by Django 5.2.5 on 2026-05-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='access_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
