# Generated by Django 6.0.2 on 2026-05-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_invoice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='access_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='invoice_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
