# Generated by Django 5.2.5 on 2026-06-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_access_key_tenant_invoice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
