# Generated by Django 5.2.5 on 2026-07-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='food_lic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
