# Generated by Django 5.2.5 on 2026-07-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_food_lic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='max_daily_scans',
            field=models.PositiveIntegerField(default=100, help_text='Maximum allowed prescription scans per day'),
        ),
    ]
