# Generated by Django 5.2.5 on 2025-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_content',
        ),
        migrations.AddField(
            model_name='products',
            name='product_content',
            field=models.ManyToManyField(blank=True, to='easypharma.productcontent'),
        ),
    ]
