# Generated by Django 5.2.5 on 2025-08-27 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0002_remove_products_product_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_content',
        ),
        migrations.AddField(
            model_name='products',
            name='product_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easypharma.productcontent'),
        ),
    ]
