# Generated by Django 5.2.5 on 2025-08-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0004_purchaseinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='total_price',
            new_name='product_total',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='product_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='product_schme_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='total_bill_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
