# Generated by Django 5.2.5 on 2025-09-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCompnay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sht_name', models.CharField(blank=True, max_length=6, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
