# Generated by Django 5.2.5 on 2025-09-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0002_drugcompnay'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='compny_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easypharma.drugcompnay'),
        ),
    ]
