# Generated by Django 6.0.2 on 2026-05-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0006_remove_purchaseinvoice_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='dl_number',
            field=models.CharField(blank=True, help_text='Drug License Number', max_length=50, null=True),
        ),
    ]
