# Generated by Django 6.0.2 on 2026-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0007_supplier_dl_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='conversion_factor',
            field=models.PositiveIntegerField(default=1, help_text='Number of units per pack (e.g. 10 tablets per strip)'),
        ),
    ]
