# Generated by Django 6.0.2 on 2026-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0008_products_conversion_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
