# Generated by Django 5.2.5 on 2026-05-13 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0009_saleinvoice_doctor_name_saleinvoice_patient_name_and_more'),
        ('tenants', '0004_tenant_access_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_inv_no', models.CharField(max_length=50, unique=True)),
                ('return_qty', models.IntegerField()),
                ('return_at', models.DateTimeField(auto_now_add=True)),
                ('sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_return', to='easypharma.saleinvoice')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
