# Generated by Django 6.0.2 on 2026-05-13 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0010_salesreturn'),
        ('tenants', '0004_tenant_access_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.PositiveIntegerField()),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypharma.saleitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='easypharma.salesreturn')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
