# Generated by Django 6.0.2 on 2026-05-14 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0012_doctormodel'),
        ('tenants', '0004_tenant_access_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('regular', 'Regular Scheme'), ('composition', 'Composition Scheme')], max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GSTConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('regular', 'Regular Scheme'), ('composition', 'Composition Scheme')], default='regular', max_length=50)),
                ('gst_number', models.CharField(max_length=15, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200, null=True)),
                ('filing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('financial_year_start_month', models.IntegerField(default=4)),
                ('financial_year_start_day', models.IntegerField(default=1)),
                ('composition_turnover_limit', models.DecimalField(decimal_places=2, default=40000000, max_digits=12)),
                ('regular_turnover_threshold', models.DecimalField(decimal_places=2, default=4000000, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'gst_number')},
            },
        ),
        migrations.CreateModel(
            name='GSTFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('gstr-1', 'GSTR-1 - Outward Supplies'), ('gstr-3b', 'GSTR-3B - Monthly Return'), ('gstr-9', 'GSTR-9 - Annual Return'), ('cmp-08', 'CMP-08 - Quarterly Return'), ('gstr-4', 'GSTR-4 - Annual Return (Composition)')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('total_taxable_supply', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gst_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gst_input_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_gst_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared'), ('filed', 'Filed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('amended', 'Amended')], default='draft', max_length=20)),
                ('filed_on', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gst_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='easypharma.gstconfiguration')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('gst_config', 'form_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='GSTCompositionReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_turnover', models.DecimalField(decimal_places=2, max_digits=15)),
                ('composition_tax_rate', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('composition_tax_liability', models.DecimalField(decimal_places=2, max_digits=15)),
                ('supplies_within_state', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('supplies_outside_state', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quarter', models.IntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('gst_filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='composition_return', to='easypharma.gstfiling')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GSTReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('due_date', 'Due Date Reminder'), ('overdue', 'Overdue Reminder'), ('filing_required', 'Filing Required')], max_length=20)),
                ('reminder_date', models.DateField()),
                ('is_notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gst_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='easypharma.gstfiling')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='GSTReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('regular', 'Regular'), ('amended', 'Amended'), ('supplementary', 'Supplementary')], default='regular', max_length=20)),
                ('intrastate_supply', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interstate_supply', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exempt_supply', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('zero_rated_supply', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_5pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_5pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_5pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_12pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_12pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_12pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_18pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_18pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_18pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_28pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_28pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_28pct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_input_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_input_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_input_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reverse_charge_applicable', models.BooleanField(default=False)),
                ('reverse_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gst_filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_details', to='easypharma.gstfiling')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
