# Generated by Django 6.0.2 on 2026-05-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0013_gstscheme_gstconfiguration_gstfiling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=20),
        ),
    ]
