# Generated by Django 6.0.2 on 2026-05-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0015_expiryreturn_expiryreturnitem_supplierledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='is_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
