# Generated by Django 6.0.2 on 2026-05-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0016_purchaseinvoice_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiryreturn',
            name='return_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
