# Generated by Django 5.2.5 on 2026-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0017_expiryreturn_return_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='patient_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
