# Generated by Django 6.0.2 on 2026-05-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0018_saleinvoice_patient_address'),
        ('tenants', '0006_tenant_access_key_tenant_invoice_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_base64', models.TextField(blank=True, help_text='Logo image stored as base64 string', null=True)),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210mm × 297mm)'), ('80mm', '80mm Thermal'), ('58mm', '58mm Thermal')], default='A4', max_length=10)),
                ('show_customer_signature', models.BooleanField(default=False)),
                ('show_pharmacist_signature', models.BooleanField(default=True)),
                ('custom_header', models.TextField(blank=True, help_text='Extra text below pharmacy name', null=True)),
                ('custom_footer', models.TextField(blank=True, help_text='Footer message on invoice', null=True)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_gst_details', models.BooleanField(default=True)),
                ('show_dl_details', models.BooleanField(default=True)),
                ('margin_top', models.IntegerField(default=10)),
                ('margin_sides', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_setup', to='tenants.tenant')),
            ],
        ),
    ]
