# Generated by Django 5.2.5 on 2026-05-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0019_printsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='voucher_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
