# Generated by Django 6.0.2 on 2026-05-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0020_purchaseinvoice_voucher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='sale_type',
            field=models.CharField(choices=[('Prescription', 'Prescription Sale'), ('Counter', 'Counter Sale')], default='Prescription', max_length=50),
        ),
    ]
