# Generated by Django 5.2.5 on 2026-05-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0021_saleinvoice_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printsetup',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4 (210mm × 297mm)'), ('80mm', '80mm Thermal'), ('58mm', '58mm Thermal'), ('8x4', 'Epson LX310 Standard (8" × 4" Dot Matrix)')], default='A4', max_length=10),
        ),
    ]
