# Generated by Django 5.2.5 on 2026-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0022_alter_printsetup_paper_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
