# Generated by Django 5.2.5 on 2026-06-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0023_alter_producttype_name'),
        ('tenants', '0006_tenant_access_key_tenant_invoice_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productschedule',
            name='schedule_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='productschedule',
            unique_together={('tenant', 'schedule_name')},
        ),
    ]
