# Generated by Django 5.2.5 on 2026-06-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0023_alter_producttype_name'),
        ('tenants', '0006_tenant_access_key_tenant_invoice_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('object_type', models.CharField(choices=[('purchase', 'Purchase')], default='purchase', max_length=50)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name', 'object_type')},
            },
        ),
    ]
