# Generated by Django 5.2.5 on 2026-06-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0024_csvimportmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvImportMapping',
        ),
    ]
