# Generated by Django 5.2.5 on 2026-06-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0024_alter_productschedule_schedule_name_and_more'),
        ('easypharma', '0025_delete_csvimportmapping'),
    ]

    operations = [
    ]
