# Generated by Django 5.2.5 on 2026-06-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0026_merge_20260606_2025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productschedule',
            unique_together=set(),
        ),
    ]
