# Generated by Django 5.2.5 on 2026-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0027_alter_productschedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printsetup',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4 (210mm × 297mm)'), ('80mm', '80mm Thermal'), ('58mm', '58mm Thermal'), ('4x6', 'Epson LX310 Standard (8" × 4" Dot Matrix)')], default='A4', max_length=10),
        ),
    ]
