# Generated by Django 5.2.5 on 2026-06-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0028_alter_printsetup_paper_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printsetup',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4 (210mm × 297mm)'), ('80mm', '80mm Thermal'), ('58mm', '58mm Thermal'), ('8x4', 'Epson LX310 Standard (8" × 4" Dot Matrix)'), ('4x6', 'Epson LX310 — 4" × 6" Standard Bill')], default='A4', max_length=10),
        ),
    ]
