# Generated by Django 5.2.5 on 2026-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0030_prescriptionreminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionreminder',
            name='customer',
        ),
        migrations.AddField(
            model_name='prescriptionreminder',
            name='patient_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
