# Generated by Django 5.2.5 on 2026-06-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0031_remove_prescriptionreminder_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=0, help_text='Minimum stock level to trigger restocking alerts'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
