# Generated by Django 5.2.5 on 2026-06-18 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0033_openingstock'),
        ('tenants', '0007_tenant_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openingstock',
            old_name='tax_percentage',
            new_name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='openingstock',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='openingstock',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='openingstock',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='openingstock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='openingstock',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='openingstock',
            name='quantity',
        ),
        migrations.AddField(
            model_name='openingstock',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='openingstock',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='openingstock',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='OpeningStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='easypharma.openingstock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypharma.products')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
