# Generated by Django 5.2.5 on 2026-06-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0034_rename_tax_percentage_openingstock_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingstockitem',
            name='sale_price',
        ),
    ]
