# Generated by Django 5.2.5 on 2026-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0035_remove_openingstockitem_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
