# Generated by Django 5.2.5 on 2026-06-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0036_salesreturn_return_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
