# Generated by Django 6.0.2 on 2026-07-10 04:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0037_alter_stockbatch_sale_price'),
        ('tenants', '0008_tenant_food_lic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_sales', models.BooleanField(default=True, verbose_name='Sales')),
                ('can_access_purchase', models.BooleanField(default=True, verbose_name='Purchase')),
                ('can_access_master', models.BooleanField(default=True, verbose_name='Master / Inventory')),
                ('can_access_reports', models.BooleanField(default=False, verbose_name='Reports')),
                ('can_access_gst', models.BooleanField(default=False, verbose_name='GST Compliance')),
                ('can_access_accounting', models.BooleanField(default=False, verbose_name='Accounting')),
                ('can_access_utility', models.BooleanField(default=False, verbose_name='Utility / Settings')),
                ('can_access_firm_details', models.BooleanField(default=False, verbose_name='Firm Details')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='User Management')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('PERM', 'Permission Change'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('module', models.CharField(choices=[('auth', 'Authentication'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('master', 'Master'), ('reports', 'Reports'), ('gst', 'GST'), ('accounting', 'Accounting'), ('utility', 'Utility'), ('users', 'User Management'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='easypharma__tenant__611985_idx'), models.Index(fields=['user', 'timestamp'], name='easypharma__user_id_484ca5_idx'), models.Index(fields=['module', 'action_type'], name='easypharma__module_4bf68a_idx')],
            },
        ),
    ]
