# Generated by Django 5.2.5 on 2026-07-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0037_alter_stockbatch_sale_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='openingstockitem',
            table='easypharma_opening_stock_item',
        ),
    ]
