# Generated by Django 6.0.2 on 2026-07-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0038_alter_openingstockitem_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierledger',
            name='transaction_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Payment', 'Payment'), ('Return', 'Return'), ('JV', 'Journal Voucher')], max_length=50),
        ),
    ]
