# Generated by Django 6.0.2 on 2026-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0040_customerledger_customerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
