# Generated by Django 6.0.2 on 2026-07-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0038_add_userpermission_activitylog'),
        ('easypharma', '0041_customerpayment_payment_details_and_more'),
    ]

    operations = [
    ]
