# Generated by Django 6.0.2 on 2026-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0043_prescriptionscanlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
