# Generated by Django 6.0.2 on 2026-07-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0044_alter_products_product_name'),
        ('tenants', '0009_tenant_max_daily_scans'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI / QR Code'), ('credit', 'Credit')], default='cash', max_length=20)),
                ('require_customer_phone', models.BooleanField(default=False, help_text='Require customer phone number on sales invoice')),
                ('print_invoice_after_save', models.BooleanField(default=True, help_text='Automatically open print dialog after saving sale')),
                ('expiry_date_format', models.CharField(choices=[('text', 'Text Input (MM/YY)'), ('dropdown', 'Months/Years Dropdown')], default='text', help_text='Choose how expiry date is entered during purchase entry', max_length=20)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Default tax rate for new products', max_digits=5)),
                ('auto_update_selling_price', models.BooleanField(default=False, help_text='Automatically adjust product selling price when purchase cost changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_setup', to='tenants.tenant')),
            ],
        ),
    ]
