# Generated by Django 6.0.2 on 2026-07-20 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0045_generalsetup'),
        ('tenants', '0009_tenant_max_daily_scans'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_code', models.CharField(help_text='e.g. 25-26 or 2025-26', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of FY (e.g. 01-Apr-2025)')),
                ('end_date', models.DateField(help_text='End date of FY (e.g. 31-Mar-2026)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Freeze Books toggle: when True, entries for this FY are locked.')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_financial_years', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Financial Year',
                'verbose_name_plural': 'Financial Years',
                'ordering': ['-start_date'],
                'unique_together': {('tenant', 'fy_code')},
            },
        ),
    ]
