# Generated by Django 5.2.5 on 2026-07-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0045_generalsetup'),
        ('tenants', '0009_tenant_max_daily_scans'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('attachment_path', models.CharField(blank=True, help_text='Local path to downloaded PDF/Image', max_length=500, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_product_name', models.CharField(help_text='Product name as read from PDF', max_length=255)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('free_quantity', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('draft_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='easypharma.draftpurchaseinvoice')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easypharma.products')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text="User's Gmail address", max_length=254)),
                ('app_password', models.CharField(help_text='Gmail 16-character App Password', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable email invoice fetching')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Timestamp of last email synchronization', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
