# Generated by Django 6.0.2 on 2026-07-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0046_financialyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='printsetup',
            name='print_single_copy',
            field=models.BooleanField(default=False, help_text='If true, prints a single copy instead of original + duplicate (For carbon paper)'),
        ),
    ]
