# Generated by Django 6.0.2 on 2026-07-28 04:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0047_printsetup_print_single_copy'),
        ('tenants', '0009_tenant_max_daily_scans'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDiscard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity in units (e.g. strips/bottles/tablets)')),
                ('discard_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discards', to='easypharma.products')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Stock Discards',
            },
        ),
    ]
