# Generated by Django 5.2.5 on 2026-07-28 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0050_prescriptionreminder_patient_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
