# Generated by Django 6.0.2 on 2026-08-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0051_alter_saleinvoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
