# Generated by Django 5.2.5 on 2026-08-20 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0052_purchaseitem_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
