# Generated by Django 5.2.5 on 2026-09-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0053_alter_saleinvoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='doctor_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
