# Generated by Django 6.0.2 on 2026-09-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypharma', '0054_doctormodel_doctor_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetup',
            name='sale_type',
            field=models.CharField(choices=[('unit', 'Unit (Tablets)'), ('strip', 'Strip / Pack')], default='unit', max_length=20),
        ),
    ]
